"""empty message

Revision ID: 600c5325f9af
Revises: 
Create Date: 2023-11-12 21:29:52.780550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600c5325f9af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('melhores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('vento', sa.Float(), nullable=True),
    sa.Column('swell', sa.Float(), nullable=True),
    sa.Column('direcao', sa.Float(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('classicos', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('melhores')
    # ### end Alembic commands ###
