"""empty message

Revision ID: e5f8690b4f83
Revises: 6c542ab8a1b4
Create Date: 2023-11-12 22:23:50.641124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f8690b4f83'
down_revision = '6c542ab8a1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altas', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vala', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.drop_column('vala')
        batch_op.drop_column('altas')

    # ### end Alembic commands ###
